# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku.ui'
#
# Created: Mon Jul 29 13:39:48 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Sudoku(object):
    def setupUi(self, Sudoku):
        Sudoku.setObjectName(_fromUtf8("Sudoku"))
        Sudoku.setWindowModality(QtCore.Qt.WindowModal)
        Sudoku.resize(833, 595)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/sudoku1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Sudoku.setWindowIcon(icon)
        Sudoku.setStyleSheet(_fromUtf8("#centralWidget{background-image: url(:/img/fondo.png)}"))
        self.centralWidget = QtGui.QWidget(Sudoku)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gLTablero = QtGui.QGridLayout()
        self.gLTablero.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gLTablero.setSpacing(1)
        self.gLTablero.setObjectName(_fromUtf8("gLTablero"))
        self.horizontalLayout.addLayout(self.gLTablero)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.glPistas = QtGui.QGridLayout()
        self.glPistas.setObjectName(_fromUtf8("glPistas"))
        self.gridLayout.addLayout(self.glPistas, 8, 0, 10, 3)
        self.pBf3 = QtGui.QPushButton(self.centralWidget)
        self.pBf3.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBf3.setIcon(icon1)
        self.pBf3.setIconSize(QtCore.QSize(48, 48))
        self.pBf3.setCheckable(False)
        self.pBf3.setFlat(True)
        self.pBf3.setObjectName(_fromUtf8("pBf3"))
        self.gridLayout.addWidget(self.pBf3, 4, 2, 1, 1)
        self.pBf4 = QtGui.QPushButton(self.centralWidget)
        self.pBf4.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBf4.setIcon(icon2)
        self.pBf4.setIconSize(QtCore.QSize(48, 48))
        self.pBf4.setCheckable(False)
        self.pBf4.setFlat(True)
        self.pBf4.setObjectName(_fromUtf8("pBf4"))
        self.gridLayout.addWidget(self.pBf4, 5, 0, 1, 1)
        self.contTiempo = QtGui.QLCDNumber(self.centralWidget)
        self.contTiempo.setObjectName(_fromUtf8("contTiempo"))
        self.gridLayout.addWidget(self.contTiempo, 0, 2, 1, 1)
        self.pBf1 = QtGui.QPushButton(self.centralWidget)
        self.pBf1.setEnabled(True)
        self.pBf1.setAutoFillBackground(False)
        self.pBf1.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBf1.setIcon(icon3)
        self.pBf1.setIconSize(QtCore.QSize(48, 48))
        self.pBf1.setCheckable(False)
        self.pBf1.setFlat(True)
        self.pBf1.setObjectName(_fromUtf8("pBf1"))
        self.gridLayout.addWidget(self.pBf1, 4, 0, 1, 1)
        self.pBf2 = QtGui.QPushButton(self.centralWidget)
        self.pBf2.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBf2.setIcon(icon4)
        self.pBf2.setIconSize(QtCore.QSize(48, 48))
        self.pBf2.setCheckable(False)
        self.pBf2.setFlat(True)
        self.pBf2.setObjectName(_fromUtf8("pBf2"))
        self.gridLayout.addWidget(self.pBf2, 4, 1, 1, 1)
        self.pBf5 = QtGui.QPushButton(self.centralWidget)
        self.pBf5.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBf5.setIcon(icon5)
        self.pBf5.setIconSize(QtCore.QSize(48, 48))
        self.pBf5.setCheckable(False)
        self.pBf5.setFlat(True)
        self.pBf5.setObjectName(_fromUtf8("pBf5"))
        self.gridLayout.addWidget(self.pBf5, 5, 1, 1, 1)
        self.pBf6 = QtGui.QPushButton(self.centralWidget)
        self.pBf6.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBf6.setIcon(icon6)
        self.pBf6.setIconSize(QtCore.QSize(48, 48))
        self.pBf6.setCheckable(False)
        self.pBf6.setFlat(True)
        self.pBf6.setObjectName(_fromUtf8("pBf6"))
        self.gridLayout.addWidget(self.pBf6, 5, 2, 1, 1)
        self.pBf7 = QtGui.QPushButton(self.centralWidget)
        self.pBf7.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/7.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBf7.setIcon(icon7)
        self.pBf7.setIconSize(QtCore.QSize(48, 48))
        self.pBf7.setCheckable(False)
        self.pBf7.setFlat(True)
        self.pBf7.setObjectName(_fromUtf8("pBf7"))
        self.gridLayout.addWidget(self.pBf7, 6, 0, 1, 1)
        self.pBf8 = QtGui.QPushButton(self.centralWidget)
        self.pBf8.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/8.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBf8.setIcon(icon8)
        self.pBf8.setIconSize(QtCore.QSize(48, 48))
        self.pBf8.setCheckable(False)
        self.pBf8.setFlat(True)
        self.pBf8.setObjectName(_fromUtf8("pBf8"))
        self.gridLayout.addWidget(self.pBf8, 6, 1, 1, 1)
        self.pBf9 = QtGui.QPushButton(self.centralWidget)
        self.pBf9.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/9.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBf9.setIcon(icon9)
        self.pBf9.setIconSize(QtCore.QSize(48, 48))
        self.pBf9.setCheckable(False)
        self.pBf9.setFlat(True)
        self.pBf9.setObjectName(_fromUtf8("pBf9"))
        self.gridLayout.addWidget(self.pBf9, 6, 2, 1, 1)
        self.btHelp = QtGui.QPushButton(self.centralWidget)
        self.btHelp.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btHelp.setIcon(icon10)
        self.btHelp.setIconSize(QtCore.QSize(60, 60))
        self.btHelp.setFlat(True)
        self.btHelp.setObjectName(_fromUtf8("btHelp"))
        self.gridLayout.addWidget(self.btHelp, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color:white"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color:white"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color:white"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color:white"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 7, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        Sudoku.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(Sudoku)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 833, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuArchivo = QtGui.QMenu(self.menuBar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        Sudoku.setMenuBar(self.menuBar)
        self.actionNuevo_Juego = QtGui.QAction(Sudoku)
        self.actionNuevo_Juego.setObjectName(_fromUtf8("actionNuevo_Juego"))
        self.actionSalir = QtGui.QAction(Sudoku)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionMostrar_Solucion = QtGui.QAction(Sudoku)
        self.actionMostrar_Solucion.setObjectName(_fromUtf8("actionMostrar_Solucion"))
        self.actionGuardar = QtGui.QAction(Sudoku)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.menuArchivo.addAction(self.actionNuevo_Juego)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuBar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(Sudoku)
        QtCore.QMetaObject.connectSlotsByName(Sudoku)

    def retranslateUi(self, Sudoku):
        Sudoku.setWindowTitle(_translate("Sudoku", "Sudoku", None))
        self.label_3.setText(_translate("Sudoku", "FICHAS", None))
        self.label.setText(_translate("Sudoku", "AYUDA", None))
        self.label_2.setText(_translate("Sudoku", "TIEMPO", None))
        self.label_4.setText(_translate("Sudoku", "PISTAS", None))
        self.menuArchivo.setTitle(_translate("Sudoku", "Archivo", None))
        self.actionNuevo_Juego.setText(_translate("Sudoku", "Nuevo Juego", None))
        self.actionSalir.setText(_translate("Sudoku", "Salir", None))
        self.actionMostrar_Solucion.setText(_translate("Sudoku", "Mostrar Solucion", None))
        self.actionGuardar.setText(_translate("Sudoku", "Guardar Partida", None))

import img_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Sudoku = QtGui.QMainWindow()
    ui = Ui_Sudoku()
    ui.setupUi(Sudoku)
    Sudoku.show()
    sys.exit(app.exec_())

